// PURPOSE: test trivial exception handling.

var error globerr;

function test_try_1( : string)
{
  try {
    system.abort("uh");
    return "a";
  } catch (error x) {
    globerr = x;
    return "b";
  }
}

assert(test_try_1() == "b");

